<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Blog:Admin:Browser@indexAction' => isset($categoryId) ? 'Go home' : null,
            'Blog:Admin:Post@addAction' => 'Add a post',
            'Blog:Admin:Category@addAction' => 'Add category',
            'Blog:Admin:Config@indexAction' => 'Configuration'
        ),

        'actions' => array(
            'data' => $posts,
            'save' => 'Blog:Admin:Post@tweakAction',
            'delete' => 'Blog:Admin:Post@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Latest posts')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($posts, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'name',
                    ),

                    array(
                        'column' => 'timestamp',
                        'label' => 'Date',
                        'value' => function($post){
                            return date('d-m-Y', $post->getTimestamp());
                        }
                    ),

                    array(
                        'column' => 'category_name',
                        'label' => 'Amount of news'
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($post){
                            return Element::checkbox(sprintf('published[%s]', $post->getId()), $post->getPublished());
                        }
                    ),

                    array(
                        'column' => 'comments',
                        'value' => function($post){
                            return Element::checkbox(sprintf('comments[%s]', $post->getId()), $post->getComments());
                        }
                    ),

                    array(
                        'column' => 'seo',
                        'label' => 'Enable SEO',
                        'value' => function($post){
                            return Element::checkbox(sprintf('seo[%s]', $post->getId()), $post->getSeo());
                        }
                    )
                ),

                'actions' => array(
                    'view' => function($post){
                        return Icon::view($post->getUrl(), $this->translate('View this post'));
                    },

                    'edit' => function($post){
                        return Icon::edit(
                            $this->url('Blog:Admin:Post@editAction', $post->getId()),
                            $this->translate('Edit this post')
                        );
                    },

                    'remove' => function($post){
                        return Icon::remove(
                            $this->url('Blog:Admin:Post@deleteAction', $post->getId()),
                            $this->translate('Remove this post')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($posts)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No posts'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>
</div>

<div class="card">
    <h4><i class="glyphicon glyphicon-th-list"></i> <?php echo $this->translate('Categories'); ?> (<?php echo count($categories); ?>)</h4>

    <?= $this->widget(new GridViewWidget($categories, array(
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'rowAttributes' => array(
            'class' => function($row) use ($categoryId){
                return $row['id'] == $categoryId ? 'success' : null;
            }
        ),

        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name',
            ),

            array(
                'column' => 'post_count',
                'label' => 'Amount of posts'
            )
        ),

        'actions' => array(
            'view' => function($category){
                return Icon::view($category['url'], $this->translate('View this category on site'));
            },

            'edit' => function($category){
                return Icon::edit(
                    $this->url('Blog:Admin:Category@editAction', $category['id']),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($category){
                return Icon::remove(
                    $this->url('Blog:Admin:Category@deleteAction', $category['id']),
                    $this->translate('Remove this category')
                );
            }
        )
    ))); ?>

    <?php if (empty($categories)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
    </div>
    <?php endif; ?>
</div>