<?php

use Krystal\Form\Element;

?>

<form data-group="config">
	<div class="well clearfix">
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Per page count'); ?></label>
			<div class="col-lg-10">
				<div class="input-group date">
                    <?php echo Element::number('config[per_page_count]', $config->getPerPageCount(), array('class' => 'form-control', 'min' => '1')); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
				<span class="help-block"><?php $this->show('How many posts you want to be displayed per page in each category?'); ?></span>
			</div>
		</div>
	</div>

	<button data-button="save" data-url="<?php echo $this->url('Blog:Admin:Config@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="cancel" data-url="<?php echo $this->url('Blog:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-open"></i> <?php $this->show('Cancel'); ?></button>

</form>