<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', [
        'items' => [
            'Blog:Admin:Browser@indexAction' => isset($categoryId) ? 'Go home' : null,
            'Blog:Admin:Post@addAction' => 'Add a post',
            'Blog:Admin:Category@addAction' => 'Add category',
            'Blog:Admin:Config@indexAction' => 'Configuration'
        ],

        'actions' => [
            'data' => $posts,
            'save' => 'Blog:Admin:Post@tweakAction',
            'delete' => 'Blog:Admin:Post@deleteAction'
        ]
    ]); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', ['caption' => 'Latest posts']); ?>

    <form class="table-responsive">
        <?= $this->widget(new GridViewWidget($posts, [
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'name',
                    'filter' => true,
                    'attributes' => [
                        'class' => null
                    ]
                ],

                [
                    'column' => 'timestamp',
                    'label' => 'Date',
                    'value' => function($post){
                        return date('d-m-Y', $post->getTimestamp());
                    }
                ],

                [
                    'column' => 'category_name',
                    'label' => 'Category'
                ],

                [
                    'column' => 'published',
                    'value' => function($post){
                        return Element::checkbox(sprintf('published[%s]', $post->getId()), $post->getPublished());
                    }
                ],

                [
                    'column' => 'comments',
                    'value' => function($post){
                        return Element::checkbox(sprintf('comments[%s]', $post->getId()), $post->getComments());
                    }
                ],

                [
                    'column' => 'seo',
                    'label' => 'Enable SEO',
                    'value' => function($post){
                        return Element::checkbox(sprintf('seo[%s]', $post->getId()), $post->getSeo());
                    }
                ]
            ],

            'actions' => [
                'view' => function($post){
                    return Icon::view($post->getUrl(), $this->translate('View this post'));
                },

                'edit' => function($post){
                    return Icon::edit(
                        $this->url('Blog:Admin:Post@editAction', $post->getId()),
                        $this->translate('Edit this post')
                    );
                },

                'remove' => function($post){
                    return Icon::remove(
                        $this->url('Blog:Admin:Post@deleteAction', $post->getId()),
                        $this->translate('Remove this post')
                    );
                }
            ]
        ])); ?>

        <?php if (empty($posts)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No posts'); ?></h2>
        </div>
        <?php endif; ?>
    </form>

    <?php $this->loadPartial('paginator'); ?>
</div>

<div class="card">
    <h4 class="mb-3 mt-2"><i class="fas fa-tags"></i> <?php $this->show('Categories'); ?> <small>(<?php echo count($categories); ?>)</small></h4>

    <?= $this->widget(new GridViewWidget($categories, [
        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
        'rowAttributes' => [
            'class' => function($row) use ($categoryId){
                return $row['id'] == $categoryId ? 'success' : null;
            }
        ],

        'columns' => [
            [
                'column' => 'id',
                'label' => '#'
            ],

            [
                'column' => 'name',
                'attributes' => [
                    'class' => null
                ]
            ],

            [
                'column' => 'post_count',
                'label' => 'Amount of posts'
            ]
        ],

        'actions' => [
            'view' => function($category){
                return Icon::view($category['url'], $this->translate('View this category on site'));
            },

            'edit' => function($category){
                return Icon::edit(
                    $this->url('Blog:Admin:Category@editAction', $category['id']),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($category){
                return Icon::remove(
                    $this->url('Blog:Admin:Category@deleteAction', $category['id']),
                    $this->translate('Remove this category')
                );
            }
        ]
    ])); ?>

    <?php if (empty($categories)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
    </div>
    <?php endif; ?>
</div>